name: decent_git
description: A decent git client

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  fluent_ui: ^4.1.1
  provider: ^6.0.3
  system_theme: ^2.0.0
  window_manager: ^0.2.7
  url_launcher: ^6.1.5
  clipboard: ^0.1.3
  http: ^0.13.4
  flutter_syntax_view:
    git:
      url: https://github.com/YehudaKremer/flutter_syntax_view.git
  libgit2dart: ^1.2.0
  easy_table: ^2.2.0
  file_picker: ^5.2.4
  flutter_acrylic: ^1.0.0+2
  shared_preferences: ^2.0.15
  async: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_native_splash: ^2.1.6
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

